# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "btrfs" "xhci_pci" "ehci_pci" "ohci_pci" "usbcore" "usb_storage" "ax88179_178a" ];
  boot.initrd.kernelModules = [  "nvme" "btrfs" "xhci_pci" "ehci_pci" "ohci_pci" "usbcore" "usb_storage" "ax88179_178a" ];
  # boot.kernelPackages is provided by nixos-hardware's raspberry-pi-5 module
  # (linux-rpi vendor fork, 6.18.x) — do not pin linuxPackages_rpi4 here or it
  # overrides the module's mkDefault and holds the kernel back at 6.12.
  boot.kernelModules = [ "nvme" "btrfs" "brcmfmac" "xhci_pci" "ehci_pci" "ohci_pci" "usbcore" "usb_storage" "ax88179_178a" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/" = {
      device = "/dev/disk/by-uuid/9c1b3848-8dde-446b-b6c4-68e80af5896d";
      fsType = "ext4";
    };
    "/boot" = {
      device = "/dev/disk/by-uuid/067A-9503";
      fsType = "vfat";
    };
    "/swap" = {
      device = "/dev/disk/by-uuid/72fe8e04-f6a0-4d2c-b121-fdb150d1b098";
      fsType = "btrfs";
      options = [ "subvol=swap" ];
    };
    "/home" = {
      device = "/dev/disk/by-uuid/72fe8e04-f6a0-4d2c-b121-fdb150d1b098";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };
    "/home/runih" = {
      device = "/dev/disk/by-uuid/72fe8e04-f6a0-4d2c-b121-fdb150d1b098";
      fsType = "btrfs";
      options = [ "subvol=runih" ];
    };
    "/home/minecraft" = {
      device = "/dev/disk/by-uuid/72fe8e04-f6a0-4d2c-b121-fdb150d1b098";
      fsType = "btrfs";
      options = [ "subvol=minecraft" "noatime" "exec" "compress=zstd" ];
    };
    "/mnt/backup" = {
      device = "192.168.7.5:/volume1/backup/";
      fsType = "nfs";
      options = [ "x-systemd.automount" "noatime" "nfsvers=4" ];
    };
  };

  swapDevices = [ {
    device = "/swap/swapfile";
  } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.end0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
