# Safe, generation-aware boot for the Raspberry Pi 5.
#
# The Pi 5 firmware boots straight from /boot/config.txt — there is no boot
# menu and nothing updates config.txt on `nixos-rebuild`. This module makes the
# update flow safe:
#
#   nixos-switch          build the new generation (nixos-rebuild boot, NO live
#                         activation), copy its kernel/initrd/dtb/overlays to
#                         /boot/gen<N>/, write /boot/tryboot.txt -> gen<N>, print
#                         the test command. Never writes /boot/config.txt.
#
#   sudo reboot "0 tryboot"   boot gen<N> exactly once. Any crash / hang /
#                         power-cycle reverts to config.txt on the next boot.
#
#   tryboot-commit.service    runs late in boot; iff we booted via tryboot AND
#                         the running system is the staged one AND we reached
#                         multi-user, it copies tryboot.txt -> config.txt.
#                         That is the ONLY thing that ever changes config.txt.
#
#   nixos-boot-status     show running / committed / staged generation.
{ config, lib, pkgs, ... }:

let
  flakeRef = "/home/runih/.config/home-manager/hosts/linux/nixos-pi5/nixos#nixos-pi5";

  # This machine's real root device + console. NixOS's own kernelParams carry
  # `root=fstab`, which the Pi firmware cannot resolve, so the root spec is
  # pinned here and the remaining NixOS params are carried through per-generation.
  cmdlineFixed =
    "console=serial0,115200n8 console=tty1 "
    + "root=PARTUUID=83ec87f5-e007-4ef3-8d59-a1ae38d764ab "
    + "rootfstype=ext4 fsck.repair=yes rootwait";

  trybootTemplate = pkgs.writeText "tryboot.txt.in" ''
    # GENERATED by nixos-switch — do not edit.
    # One-shot boot of a freshly built NixOS generation:
    #     sudo reboot "0 tryboot"
    # On a boot that reaches multi-user, tryboot-commit.service copies this file
    # to config.txt. Any failure or power-cycle keeps the current config.txt.
    [all]
    arm_64bit=1
    enable_uart=1
    avoid_warnings=1
    camera_auto_detect=0
    display_auto_detect=1
    disable_overscan=1
    os_prefix=@DIR@/
    kernel=Image
    initramfs initrd followkernel
    dtoverlay=vc4-kms-v3d-pi5
  '';

  stage = pkgs.writeShellApplication {
    name = "nixos-stage-tryboot";
    runtimeInputs = [ pkgs.coreutils pkgs.gnused pkgs.gnugrep ];
    text = ''
      # Stage the current system-profile generation for a tryboot test.
      # Runs as root. Never touches /boot/config.txt.
      if [ "$(id -u)" != 0 ]; then echo "must run as root" >&2; exit 1; fi

      BOOT=/boot
      SYS=$(readlink -f /nix/var/nix/profiles/system)
      link=$(readlink /nix/var/nix/profiles/system)   # system-<N>-link
      gen=''${link#system-}; gen=''${gen%-link}
      dir="gen''${gen}"

      echo "staging generation ''${gen}"
      echo "  system : $SYS"
      echo "  ->     : $BOOT/$dir/"

      install -d -m 0755 "$BOOT/$dir/overlays"
      cp -Lf  "$SYS/kernel"                      "$BOOT/$dir/Image"
      cp -Lf  "$SYS/initrd"                      "$BOOT/$dir/initrd"
      cp -Lf  "$SYS"/dtbs/broadcom/bcm2712*.dtb  "$BOOT/$dir/"
      cp -Lrf "$SYS"/dtbs/overlays/.             "$BOOT/$dir/overlays/"

      carried=$(tr ' ' '\n' < "$SYS/kernel-params" | grep -vE '^(root|init)=' | tr '\n' ' ')
      echo "${cmdlineFixed} ''${carried}init=$SYS/init boot.shell_on_fail" \
        > "$BOOT/$dir/cmdline.txt"

      sed "s#@DIR@#''${dir}#" ${trybootTemplate} > "$BOOT/tryboot.txt"

      # keep only the committed gen dir and the one just staged
      committed=$(sed -n 's#^os_prefix=\(gen[0-9]\+\)/#\1#p' "$BOOT/config.txt" || true)
      for d in "$BOOT"/gen[0-9]*; do
        [ -d "$d" ] || continue
        b=$(basename "$d")
        if [ "$b" != "$dir" ] && [ "$b" != "$committed" ]; then
          echo "  pruning stale $b"
          rm -rf "$d"
        fi
      done
      sync

      echo
      echo "=================================================================="
      echo " generation ''${gen} built + staged   (NOT active yet)"
      echo
      echo "   test:    sudo reboot \"0 tryboot\""
      echo "   commit:  automatic once gen ''${gen} reaches multi-user"
      echo "   abort:   reboot normally / pull power -> stays on ''${committed:-current}"
      echo
      echo " /boot/config.txt currently boots:  ''${committed:-<unknown>}"
      echo "=================================================================="
    '';
  };

  switch = pkgs.writeShellApplication {
    name = "nixos-switch";
    runtimeInputs = [ ];
    text = ''
      echo ">> nixos-rebuild boot  (build new generation, no live activation)"
      sudo nixos-rebuild boot --flake ${flakeRef} "$@"
      sudo ${stage}/bin/nixos-stage-tryboot
    '';
  };

  status = pkgs.writeShellApplication {
    name = "nixos-boot-status";
    runtimeInputs = [ pkgs.coreutils pkgs.gnused ];
    text = ''
      BOOT=/boot
      prefix() { sed -n 's#^os_prefix=\(gen[0-9]\+\)/#\1#p' "$1" 2>/dev/null || true; }
      echo "running system : $(readlink -f /run/current-system)"
      echo "booted system  : $(readlink -f /run/booted-system)"
      echo "newest profile : $(readlink /nix/var/nix/profiles/system)"
      echo "config.txt     : $(prefix "$BOOT/config.txt")   <- a normal reboot boots this"
      echo "tryboot.txt    : $(prefix "$BOOT/tryboot.txt")   <- 'sudo reboot \"0 tryboot\"' boots this"
    '';
  };

  commit = pkgs.writeShellApplication {
    name = "tryboot-commit";
    runtimeInputs = [ pkgs.coreutils pkgs.gnused pkgs.gnugrep pkgs.systemd ];
    text = ''
      BOOT=/boot
      DT=/proc/device-tree/chosen
      log() { echo "tryboot-commit: $*"; }

      # 1. did the firmware boot us with the one-shot tryboot flag?
      flag=""
      if [ -e "$DT/bootloader/tryboot" ]; then
        flag=$(od -An -tx1 < "$DT/bootloader/tryboot" | tr -d ' \n')
      fi
      if [ "$flag" != "00000001" ]; then
        log "normal boot (tryboot flag: ''${flag:-none}); nothing to do"
        exit 0
      fi

      # 2. which os_prefix is being tested? prefer what the firmware recorded,
      #    fall back to what tryboot.txt declares (that's the file it just used).
      osp=""
      if [ -e "$DT/os_prefix" ]; then
        osp=$(tr -d '\0' < "$DT/os_prefix")
      fi
      if [ -z "$osp" ]; then
        osp=$(sed -n 's#^os_prefix=\(gen[0-9]\+/\)#\1#p' "$BOOT/tryboot.txt" | head -n1)
      fi
      if [ -z "$osp" ] || [ ! -f "$BOOT/''${osp}cmdline.txt" ]; then
        log "cannot determine the staged generation (os_prefix='$osp'); not committing"
        exit 0
      fi
      log "booted via tryboot, os_prefix=$osp"

      # 3. the real safety check: the RUNNING system must be the staged one
      running=$(readlink -f /run/current-system)
      want=$(sed -n 's/.*init=\([^ ]*\).*/\1/p' "$BOOT/''${osp}cmdline.txt" | head -n1)
      if [ "$want" != "$running/init" ]; then
        log "running system ($running/init) is not the staged one ($want); not committing"
        exit 0
      fi

      # 4. we reached this unit => boot got to multi-user. Commit.
      state=$(systemctl is-system-running 2>/dev/null || true)
      log "reached multi-user (system state: ''${state:-unknown}); committing"

      if [ "$(cat "$BOOT/tryboot.txt")" = "$(cat "$BOOT/config.txt")" ]; then
        log "config.txt already matches tryboot.txt; nothing to do"
        exit 0
      fi
      cp -a "$BOOT/config.txt" "$BOOT/config.txt.prev"
      cp "$BOOT/tryboot.txt" "$BOOT/config.txt"
      sync
      log "committed $osp -> /boot/config.txt (previous saved as /boot/config.txt.prev)"
    '';
  };
in
{
  environment.systemPackages = [ switch stage status commit ];

  systemd.services.tryboot-commit = {
    description = "Commit a tryboot-tested NixOS generation to /boot/config.txt";
    wantedBy = [ "multi-user.target" ];
    after = [ "multi-user.target" ];
    unitConfig.ConditionPathExists = "/proc/device-tree/chosen/bootloader/tryboot";
    serviceConfig = {
      Type = "oneshot";
      RemainAfterExit = true;
      RequiresMountsFor = "/boot";
      ExecStart = "${commit}/bin/tryboot-commit";
    };
  };
}
